### ISSUE TITLE
A request for a nuget release

### ISSUE THREAD

**Issue by razzmatazz** [ionide/LanguageServerProtocol#1]
Would it be possible to have this released as a nuget?
Or do I need to use PAKET or FAKE (I am not versed in those build tools) to add this as a source-dependency?

I am trying to use this as per this comment:
- https://github.com/fsharp/FsAutoComplete/issues/849#issuecomment-965853373

**Comment by Krzysztof-Cieslak** [comment]
Published here: https://www.nuget.org/packages/Ionide.LanguageServerProtocol/
