### ISSUE TITLE
Out of order message processing and parallelism

### ISSUE THREAD

**Issue by artempyanykh** [ionide/LanguageServerProtocol#14]
Version I'm using is 0.3.1. I see there were quite some changes in master since then, so please let me know this is not an issue anymore.

**Context**: 
I'm trying to implement an LSP server using this library. My server supports incremental text sync, which means that fast typing leads to many textChangeEvent notifications being sent to the server. 

**Problem**:
I'm noticing that text change notifications are processed out of order, e.g.
Change(v=234)
Change(v=232)
Change(v=233)

This messes up the state.

IIUC [here](https://github.com/ionide/LanguageServerProtocol/blob/v0.3.1/src/LanguageServerProtocol.fs#L2982) each async notification handler is forked into a task, which leads to the issue.

**Describe the solution you'd like**
Having control over the parallelism of message processing would be great.

**Describe alternatives you've considered**
Unlike with requests, notifications don't have any `id` so I don't see a way to buffer things on the side of `LspServer` implementation.

**Comment by razzmatazz** [comment]
Are you using code from `master` or 0.3.1 from nuget?

[This commit](https://github.com/ionide/LanguageServerProtocol/commit/425ccf87e16f11b5ee0657330958f11fb0b31d2f)  in master moves processing of json rpc to [StreamJsonRpc](https://github.com/microsoft/vs-streamjsonrpc) and I am using this in [csharp-ls](https://github.com/razzmatazz/csharp-language-server).

I believe we have sequencing working properly in csharp-ls which uses incremental sync too. There are still some weird out-of-sync issues in emacs, but not sure what is causing them -- anyway it should be better with the latest commit, as it adds cancellation support too.

**Comment by baronfel** [comment]
Oh man, we still need to release that work, don't we @razzmatazz? I'll try to get on that soon.

**Comment by razzmatazz** [comment]
> Oh man, we still need to release that work, don't we @razzmatazz? I'll try to get on that soon.

I think so, we're using it with csharp-ls for some time, but FYI that thing still needs love:
 - Ionide.LSP.Server is NOT yet converted (leaving this to you :) ) -- as I don't have harnesses to test it;
 - there are problems with how cancellation is reported and I probably don't understand TaskCancelledException / vs AggregateException / vs OperationCanceledException where we need to set RPC errorCode to 32800 for timeouts:
   - reported here https://github.com/razzmatazz/csharp-language-server/issues/32

**Comment by artempyanykh** [comment]
> Are you using code from master or 0.3.1 from nuget?

0.3.1 from nuget. I tried setting up the one from `master` but there were some changes around `defaultHandlings` and it doesn't quite fit what `Server.start` wants from `handlings` parameter; so I put it off.

**Comment by artempyanykh** [comment]
> do you remember what it was? I probably broke defaultHandlings when trying to convert to StreamJsonRpc and fsac will hit the same issue

`requestHandlings : Map<string,Delegate>` vs `defaultRequestHandlings () : Map<string, ServerRequestHandling<'server>>`

**Comment by artempyanykh** [comment]
I've now rebased all the stuff on top of main and with #16 the server compiles fine. Going to look at the message ordering now.

**Comment by baronfel** [comment]
Here's a link to how F# async's don't handle exception propogation from Tasks the same way as C# task awaiting does: https://github.com/fsharp/fslang-suggestions/issues/840

**Comment by artempyanykh** [comment]
Probably the same problem with exception propagation, but I see that exceptions in my server's handlers are swallowed (only found this out by hooking into a running process with a debugger).

**Comment by artempyanykh** [comment]
> Going to look at the message ordering now.

I did some light manual testing against Emacs LSP and text sync worked OK: messages were delivered and processed in a proper order.

**Comment by baronfel** [comment]
Going to close this with the move to streamjsonrpc.
