### ISSUE TITLE
Is there any plan to implement call hierarchy and type hierarchy?

### ISSUE THREAD

**Issue by tcx4c70** [ionide/LanguageServerProtocol#45]
**Is your feature request related to a problem? Please describe.**
I'm going to implement call hierarchy and type hierarchy for a project which depends on this library. However, I find that the library doesn't support the 2 features at all.

So is there any plan to support the 2 features?

**Comment by baronfel** [comment]
It's just a gap - if you wanted to add the two calls and their associated types I'd merge it in a heartbeat.
