### ISSUE TITLE
`$/cancelRequest` client notification support

### ISSUE THREAD

**Issue by razzmatazz** [ionide/LanguageServerProtocol#5]
I was working a bit on trying to handle cancellation via `Async.CancellationToken` in my server project. But *apparently* (please correct me if I'm wrong) `$/cancelRequest` notification is not handled.

Is this correct, or am I using it wrong?

I am trying to acquire `CancellationToken` on my handler like this:
```fsharp
let! cs = Async.CancellationToken
```

IMHO the server library should provide proper CancellationToken support via `Async.CancellationToken` or by similar means so we can cancel heavyweight requests from client side, when e.g. the user closes text editor window but the codelens request is still pending the response.

I could try to hack this is, but I am F#/Async newbie and would need some guidance.

**Comment by baronfel** [comment]
This is covered now by streamjsonrpc, yeah?
