### ISSUE TITLE
Allow Multiple Servers Executing On Same Process

### ISSUE THREAD

**Issue by TrevorThoele2** [ionide/LanguageServerProtocol#50]
It is not possible to create the server multiple times on the same process. The problem is that the json formatter is a singleton.

We discovered this when we were making test cases around startWithSetup and the singleton causes it to crash.

**Comment by zZeck** [comment]
[This is the cause of the problem](https://learn.microsoft.com/en-us/dotnet/api/streamjsonrpc.jsonmessageformatter?view=streamjsonrpc-2.9#remarks). We have tests that communicate with the server using anonymous pipes for streams. We start and shutdown the server code each test, and did not want to use a subprocess so it is easier to debug.
